# Generated by Django 5.2.8 on 2025-11-19 05:42

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gyms',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
