# Generated by Django 5.2.8 on 2025-11-19 08:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gym',
            unique_together={('owner', 'name')},
        ),
    ]
